### ISSUE TITLE
Value cannot be null. Parameter name: standardFontMetrics

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#132]
Getting error in this document:

https://drive.google.com/open?id=1p8Qgbq65GODHMYozOvhcTdtKA8VGdLxM

Code:
            PdfDocument doc = PdfDocument.Open(@"C:\font_error.pdf");
            var page = doc.GetPage(1);

Error:
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.

Parameter name: standardFontMetrics
  Source=UglyToad.PdfPig

  StackTrace:
   at UglyToad.PdfPig.PdfFonts.Simple.Type1Standard14Font..ctor(AdobeFontMetrics standardFontMetrics, Encoding overrideEncoding) in C:\Users\Quad\Downloads\PdfPig-master\src\UglyToad.PdfPig\PdfFonts\Simple\Type1Standard14Font.cs:line 26
   at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type1FontHandler.Generate(DictionaryToken dictionary, Boolean isLenientParsing) in C:\Users\Quad\Downloads\PdfPig-master\src\UglyToad.PdfPig\PdfFonts\Parser\Handlers\Type1FontHandler.cs:line 53
   at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary, Boolean isLenientParsing) in C:\Users\Quad\Downloads\PdfPig-master\src\UglyToad.PdfPig\PdfFonts\FontFactory.cs:line 51
   at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary, Boolean isLenientParsing) in C:\Users\Quad\Downloads\PdfPig-master\src\UglyToad.PdfPig\Content\ResourceStore.cs:line 154
   at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary, Boolean isLenientParsing) in C:\Users\Quad\Downloads\PdfPig-master\src\UglyToad.PdfPig\Content\ResourceStore.cs:line 46
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean isLenientParsing) in C:\Users\Quad\Downloads\PdfPig-master\src\UglyToad.PdfPig\Parser\PageFactory.cs:line 66
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber) in C:\Users\Quad\Downloads\PdfPig-master\src\UglyToad.PdfPig\Content\Pages.cs:line 69
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) in C:\Users\Quad\Downloads\PdfPig-master\src\UglyToad.PdfPig\PdfDocument.cs:line 158
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\Quad\Downloads\PdfPig-master\src\ConsoleApp1\Program.cs:line 15
```

**Comment by EliotJones** [comment]
I've pushed up a change for this, when you get time could you give it a try and let me know if it works for you please?

**Comment by vadik299** [comment]
Works great! Thank you so much for fixing it so quickly!
