### ISSUE TITLE
Indirect reference to an undefined object behavior

### ISSUE THREAD

**Issue by Poltuu** [UglyToad/PdfPig#189]
I stumbled upon an error on a specific pdf using `document.GetPages()`.

The error occurs because the fonts node
```
/Font <<
/F0 8 0 R
/F1 9 0 R
/F2 10 0 R
/F3 0 0 R
>>
```

makes reference to an undefined font `/F3 0 0 R`.
This ends up failing  with the following stack
```
   at UglyToad.PdfPig.Tokenization.Scanner.PdfTokenScanner.Get(IndirectReference reference)
   at UglyToad.PdfPig.Parser.Parts.DirectObjectFinder.Get[T](IToken token, IPdfTokenScanner scanner)
   at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.<GetPages>d__32.MoveNext()
```

I looked at the doc, and it seems that the official behavior would be to make a reference to null, cf https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf

I'm more than willing to propose a PR if that works for you.

**Comment by EliotJones** [comment]
Hi, thanks for your issue report. If you have a PR that would be fantastic, otherwise I can try to fix it this weekend. Feel free to open a PR if you have time :)

**Comment by Poltuu** [comment]
I'm unable to push a branch, you may need to add me as a contributor ?

**Comment by InusualZ** [comment]
> 
> 
> I'm unable to push a branch (github rejects it), you may need to add me as a contributor ?

You should send a Pull Request. So we can review your changes first

**Comment by Poltuu** [comment]
:suspect: but how would I send a pull request if i'm unable to push my branch into the repository 🤔

**Comment by EliotJones** [comment]
Hi @Poltuu, first you'd need to fork the repository to one you control, once that's created you can make the changes to your repository. Once the pull request is ready to submit you can make a PR from your fork to this one: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Let me know if you run into any issues.

**Comment by Poltuu** [comment]
thanks you, learning every day 👍
