### ISSUE TITLE
Exception when attempting to parse PDF document

### ISSUE THREAD

**Issue by jgylta** [UglyToad/PdfPig#191]
When calling `document.GetPages()` on a pdf document, PdfPig throws the following exception:

```
Could not find the object 15 0 with type StreamToken.
   at UglyToad.PdfPig.Parser.Parts.DirectObjectFinder.Get[T](IToken token, IPdfTokenScanner scanner)
   at UglyToad.PdfPig.PdfFonts.Parser.Parts.CidFontFactory.GetCharacterIdentifierToGlyphIndexMap(DictionaryToken dictionary)
   at UglyToad.PdfPig.PdfFonts.Parser.Parts.CidFontFactory.Generate(DictionaryToken dictionary)
   at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type0FontHandler.ParseDescendant(DictionaryToken dictionary)
   at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type0FontHandler.Generate(DictionaryToken dictionary)
   at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ProcessFormXObject(StreamToken formStream)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ApplyXObject(NameToken xObjectName)
   at UglyToad.PdfPig.Graphics.Operations.InvokeNamedXObject.Run(IOperationContext operationContext)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ProcessOperations(IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.Process(Int32 pageNumberCurrent, IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Parser.PageFactory.GetContent(Int32 pageNumber, IReadOnlyList`1 contentBytes, CropBox cropBox, UserSpaceUnit userSpaceUnit, PageRotationDegrees rotation, Boolean clipPaths, MediaBox mediaBox)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.<GetPages>d__32.MoveNext()
```

Any help would be appreciated.

**Comment by EliotJones** [comment]
Hi @jgylta sorry to hear you're encountering this issue. Without the document that's causing this problem it's difficult to guess at the exact cause. I've tried fixing the most likely issue, would you be able to try the attached NuGet package and let me know if it resolves the problem, or providing the PDF document which replicates the error:

[PdfPig.0.1.2-bugfix161.zip](https://github.com/UglyToad/PdfPig/files/4943772/PdfPig.0.1.2-bugfix161.zip)

**Comment by jgylta** [comment]
Thank you very much. The attached packaged solved the problem and I’m now able to parse the specific documents.
