### ISSUE TITLE
GetPage fails with error "Could not find a name for this font"

### ISSUE THREAD

**Issue by andrewjsaid** [UglyToad/PdfPig#2]
Steps to reproduce:

1. Download this PDF File: [Tackling the Poor Assumptions of Naive Bayes Text Classiﬁers](http://www.aaai.org/Papers/ICML/2003/ICML03-081.pdf)
2. Call `PdfDocument.Open(...)`
3. Call document.GetPage(1)

The call to GetPage fails with the following error:
<pre>
UglyToad.PdfPig.Fonts.Exceptions.InvalidFontFormatException: Could not find a name for this font (/Type, /Font) (/Subtype, /Type1) (/FirstChar, COSInt{0}) (/LastChar, COSInt{127}) (/Widths, COSObject{325, 0}) (/BaseFont, COSObject{331, 0}) (/FontDescriptor, COSObject{332, 0}) .
   at UglyToad.PdfPig.Fonts.Parser.FontDictionaryAccessHelper.GetName(PdfDictionary dictionary, FontDescriptor descriptor)
   at UglyToad.PdfPig.Fonts.Parser.Handlers.Type1FontHandler.Generate(PdfDictionary dictionary, IRandomAccessRead reader, Boolean isLenientParsing)
   at UglyToad.PdfPig.Fonts.FontFactory.Get(PdfDictionary dictionary, IRandomAccessRead reader, Boolean isLenientParsing)
   at UglyToad.PdfPig.Content.ResourceContainer.LoadFontDictionary(PdfDictionary fontDictionary, IRandomAccessRead reader, Boolean isLenientParsing)
   at UglyToad.PdfPig.Content.ResourceContainer.LoadResourceDictionary(PdfDictionary dictionary, IRandomAccessRead reader, Boolean isLenientParsing)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, PdfDictionary dictionary, PageTreeMembers pageTreeMembers, IRandomAccessRead reader, Boolean isLenientParsing)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber)
   at FactReapUsage.Program.Main(String[] args) in C:\Code\FactReapUsage\FactReapUsage\FactReapUsage\Program.cs:line 19
</pre>

**Comment by EliotJones** [comment]
Thank you for this. I solved the initial issue which was due to not using ```DirectObjectFinder``` to retrieve the name for Type 1 fonts.

This file uses a Type 1 font which does not provide an encoding or a unicode cmaps so in order to extract the text content I need to add a Type1 font parser. This file is the first instance I've seen of this behaviour so I will implement this now.

In the meantime I've put a quick hack in which extracts the text, however it does not work for the "fi" ligature which is present in this file instead producing a weird symbol. I've attached a nuget package with this fix but it won't help much for this file.

[PdfPig.0.0.1-alpha-001-patched.zip](https://github.com/UglyToad/PdfPig/files/1628722/PdfPig.0.0.1-alpha-001-patched.zip)

**Comment by EliotJones** [comment]
I put together something very quickly today which works for this file but may not work correctly for all Type1 fonts. I will need to find and test some more. These changes will be in the next alpha release.

In the meantime the patched nuget package is attached.
[PdfPig.0.0.1-alpha-001-patched-issue1.zip](https://github.com/UglyToad/PdfPig/files/1629686/PdfPig.0.0.1-alpha-001-patched-issue1.zip)
