### ISSUE TITLE
InvalidOperationException when trying to get page

### ISSUE THREAD

**Issue by krt-** [UglyToad/PdfPig#202]
On some PDFs exception is thrown when trying to enumerate through pages.

NuGet package ver. 0.1.2

```
InvalidOperationException: Sequence contains no elements

Stacktrace:
`   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at UglyToad.PdfPig.PdfFonts.Cmap.CMap..ctor(CharacterIdentifierSystemInfo info, Int32 type, Int32 wMode, String name, String version, IReadOnlyDictionary`2 baseFontCharacterMap, IReadOnlyList`1 codespaceRanges, IReadOnlyList`1 cidRanges, IReadOnlyList`1 cidCharacterMappings) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\PdfFonts\Cmap\CMap.cs:line 81
   at UglyToad.PdfPig.PdfFonts.Cmap.CharacterMapBuilder.Build() in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\PdfFonts\Cmap\CharacterMapBuilder.cs:line 79
   at UglyToad.PdfPig.PdfFonts.Parser.CMapParser.Parse(IInputBytes inputBytes) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\PdfFonts\Parser\CMapParser.cs:line 120
   at UglyToad.PdfPig.PdfFonts.Cmap.CMapCache.Parse(IInputBytes bytes) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\PdfFonts\Cmap\CMapCache.cs:line 39
   at UglyToad.PdfPig.PdfFonts.Parser.Handlers.TrueTypeFontHandler.Generate(DictionaryToken dictionary) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\PdfFonts\Parser\Handlers\TrueTypeFontHandler.cs:line 115
   at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\PdfFonts\FontFactory.cs:line 44
   at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\Content\ResourceStore.cs:line 154
   at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\Content\ResourceStore.cs:line 46
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\Parser\PageFactory.cs:line 65
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\Content\Pages.cs:line 66
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\PdfDocument.cs:line 169
   at UglyToad.PdfPig.PdfDocument.<GetPages>d__32.MoveNext() in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\PdfDocument.cs:line 180`
```

**Comment by EliotJones** [comment]
Sorry for the delay, would you be able to try this NuGet and let me know if the error is fixed or the exception changes, thanks.

https://www.nuget.org/packages/PdfPig/0.1.3-alpha001

**Comment by krt-** [comment]
Thanks, this version does not crash anymore.
