### ISSUE TITLE
Unhandled exception. UglyToad.PdfPig.Core.PdfDocumentFormatException: Could not find the object 15 0 with type DictionaryToken.

### ISSUE THREAD

**Issue by Platzer** [UglyToad/PdfPig#208]
I get following exception when calling `UglyToad.PdfPig.PdfDocument.GetPage`:
```
Unhandled exception. UglyToad.PdfPig.Core.PdfDocumentFormatException: Could not find the object 15 0 with type DictionaryToken.
   at UglyToad.PdfPig.Parser.Parts.DirectObjectFinder.Get[T](IToken token, IPdfTokenScanner scanner)
   at UglyToad.PdfPig.PdfFonts.Parser.EncodingReader.Read(DictionaryToken fontDictionary, FontDescriptor descriptor, Encoding fontEncoding)
   at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type1FontHandler.Generate(DictionaryToken dictionary)
   at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at PdfPigPoc.Program.Main(String[] args) in C:\temp\20200831\PdfPigPoc\Program.cs:line 15
```

I'm sorry but I cannot provide the PDF because it contains sensitive data, but this is the PDF object `15 0`:
```
15 0 obj
/WinAnsiEncoding
endobj
```

Let me know how I can help to narrow the problem down.

**Comment by EliotJones** [comment]
Hi @Platzer, sorry to hear you're encountering this issue.

Thank you very much for providing the object snippet, I know exactly what should fix that. I'll try and take a look in the next couple of days.

**Comment by NelsonBittencourt** [comment]
Same problem here with object 3 0.

1) The object is:

3 0 obj
/WinAnsiEncoding
endobj

2) VS 2019 Exception details:

UglyToad.PdfPig.Core.PdfDocumentFormatException
  HResult=0x80131500
  Message=Could not find the object 3 0 with type DictionaryToken.
  Source=UglyToad.PdfPig
  StackTrace:
   em UglyToad.PdfPig.Parser.Parts.DirectObjectFinder.Get[T](IToken token, IPdfTokenScanner scanner)
   em UglyToad.PdfPig.PdfFonts.Parser.EncodingReader.Read(DictionaryToken fontDictionary, FontDescriptor descriptor, Encoding fontEncoding)
   em UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type1FontHandler.Generate(DictionaryToken dictionary)
   em UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary)
   em UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary)
   em UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary)
   em UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths)
   em UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths)
   em UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)

**Comment by scottk4016** [comment]
Similar problem iterating over GetPages() 

```
UglyToad.PdfPig.Core.PdfDocumentFormatException
  HResult=0x80131500
  Message=Could not find the object 9 0 with type DictionaryToken.
  Source=UglyToad.PdfPig
  StackTrace:
   at UglyToad.PdfPig.Parser.Parts.DirectObjectFinder.Get[T](IToken token, IPdfTokenScanner scanner)
   at UglyToad.PdfPig.PdfFonts.Parser.EncodingReader.Read(DictionaryToken fontDictionary, FontDescriptor descriptor, Encoding fontEncoding)
   at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type1FontHandler.Generate(DictionaryToken dictionary)
   at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.<GetPages>d__32.MoveNext()
   at PdfTest.Program.Main(String[] args) in C:\Users\Scott\source\repos\PdfTest\PdfTest\Program.cs:line 14
```

The object is:

```
9 0 obj
/WinAnsiEncoding
endobj
```

**Comment by EliotJones** [comment]
Hi, it turns out I was too ambitious when I thought this would be an easy fix. I've made a change to try and get some more informative errors out. The changes are in this branch: https://github.com/UglyToad/PdfPig/tree/debug-encoding-locator-issue or in the attached NuGet. If someone can try them out and let me know which error they get that would be a huge help, thanks.

[PdfPig.0.1.2.208.zip](https://github.com/UglyToad/PdfPig/files/5169438/PdfPig.0.1.2.208.zip)

**Comment by NelsonBittencourt** [comment]
Hi @EliotJones, the changes solved my problem. I will keep testing in other files with same encoding.
Thank you!

**Comment by scottk4016** [comment]
That fixed the problem for me too. It was only failing on some files and now works with all the samples I have used

**Comment by EliotJones** [comment]
I was confused why this fixed the problem, but just realised it was actually fixed by @everharder in https://github.com/UglyToad/PdfPig/pull/200

I've pushed a version with this fix to NuGet: https://www.nuget.org/packages/PdfPig/0.1.3-alpha001

**Comment by Platzer** [comment]
Sorry for the delay! Works perfectly fine on my doc too 🎉 thanks for your effort!
