### ISSUE TITLE
Error on Get.Pages() 

### ISSUE THREAD

**Issue by Smurfj3** [UglyToad/PdfPig#218]
Hello I am loving PDF pig so far threw like 200 different pdf's at it no problem but now ran into 1 that is giving an error:

`UglyToad.PdfPig.Core.PdfDocumentFormatException
  HResult=0x80131500
  Message=Could not find the object 2 0 with type DictionaryToken.
  Source=UglyToad.PdfPig
  StackTrace:
   at UglyToad.PdfPig.Parser.Parts.DirectObjectFinder.Get[T](IToken token, IPdfTokenScanner scanner)
   at UglyToad.PdfPig.PdfFonts.Parser.EncodingReader.Read(DictionaryToken fontDictionary, FontDescriptor descriptor, Encoding fontEncoding)
   at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type1FontHandler.Generate(DictionaryToken dictionary)
   at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary)
   at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.<GetPages>d__32.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at pdftest.test.<Scan>d__33.MoveNext() in \pdftest\test.cs:line 251
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at pdftest.test.<OnQueue>d__31.MoveNext() in \pdftest\test.cs:line 209`

It is not the biggest issue for what I am using this for since the majority of pdf's work fine, but I figured it be useful for you guys to know this.

**Comment by EliotJones** [comment]
Hi @Smurfj3 thanks for the issue report, I think this is the same problem encountered in https://github.com/UglyToad/PdfPig/issues/208, if you're able to would you be able to try updating to the latest pre-release NuGet package https://www.nuget.org/packages/PdfPig/0.1.3-alpha001 which should fix this please? Let me know if it doesn't fix the problem and I'll take another look, thanks :)

**Comment by Smurfj3** [comment]
> 
> 
> Hi @Smurfj3 thanks for the issue report, I think this is the same problem encountered in #208, if you're able to would you be able to try updating to the latest pre-release NuGet package https://www.nuget.org/packages/PdfPig/0.1.3-alpha001 which should fix this please? Let me know if it doesn't fix the problem and I'll take another look, thanks :)

So sorry for my late reply, I was just reporting it to be helpful, totally forgot about it because it only happened to me like once over like 1000 pdf's. Anyways, YES the latest pre-release fixes the issue! Thank you so much.

**Comment by EliotJones** [comment]
Thanks for confirming, I'll close this now :)

**Comment by etgregor** [comment]
Hello, I use the version 0.1.7, an the error appears:

`   UglyToad.PdfPig.Core.PdfDocumentFormatException: Invalid ColorSpace array encountered in page resource dictionary: [ 215 0 ].
   at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.GetPages()+MoveNext()
   at beetml.ocr.engine.Pdf.PdfUtility.ReadFile(String filePath, ILogger logger) in .../Pdf/PdfUtility.cs:line 97` 


note: Sorry, I can't share the PDF because it contains private data.
