### ISSUE TITLE
Issue reading one PDF from Pubmed

### ISSUE THREAD

**Issue by christopher5106** [UglyToad/PdfPig#292]
Hi,

Trying to read this document
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2562783/pdf/ymj-46-585.pdf

and getting the following error:

```
2021-02-18 19:43:53.9000 Document.GetPages failed :- FileName : "16259055.pdf" System.IO.EndOfStreamException: Could not read a buffer of 25445 bytes.
at UglyToad.PdfPig.Fonts.TrueType.TrueTypeDataBytes.ReadBuffered(Byte[] buffer, Int32 length)
at UglyToad.PdfPig.Fonts.TrueType.TrueTypeDataBytes.ReadString(Int32 bytesToRead, Encoding encoding)
at UglyToad.PdfPig.Fonts.TrueType.Parser.NameTableParser.Parse(TrueTypeHeaderTable header, TrueTypeDataBytes data, Builder register)
at UglyToad.PdfPig.Fonts.TrueType.Parser.TableParser.Parse[T](TrueTypeHeaderTable table, TrueTypeDataBytes data, Builder register)
at UglyToad.PdfPig.Fonts.TrueType.Parser.TrueTypeFontParser.ParseTables(Single version, IReadOnlyDictionary2 tables, TrueTypeDataBytes data) at UglyToad.PdfPig.Fonts.TrueType.Parser.TrueTypeFontParser.Parse(TrueTypeDataBytes data) at UglyToad.PdfPig.PdfFonts.Parser.Parts.CidFontFactory.ReadDescriptorFile(FontDescriptor descriptor) at UglyToad.PdfPig.PdfFonts.Parser.Parts.CidFontFactory.Generate(DictionaryToken dictionary) at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type0FontHandler.ParseDescendant(DictionaryToken dictionary) at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type0FontHandler.Generate(DictionaryToken dictionary) at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary) at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary) at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary) at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths) at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths) at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) at **UglyToad.PdfPig.PdfDocument.GetPages()+MoveNext() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
**at PdfToJsonExporter.Application.GetPages(PdfDocument pdfDocument, FileInfo fileInfo) in D:\cbo\Projects\PdfToJsonExporter\Application.cs:line 168
```

The code I'm using is:

`pages = pdfDocument.GetPages().ToList();`

**Comment by christopher5106** [comment]
Thank you, correction is valid.
