### ISSUE TITLE
Could not find the font with name in the resource store

### ISSUE THREAD

**Issue by christopher5106** [UglyToad/PdfPig#298]
On document https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2835024/pdf/mt2009176a.pdf
I get the following error :

```
2021-02-22 16:25:33.4397 GetPages failed :- FileName : "mt2009176a.pdf" System.InvalidOperationException: Could not find the font with name /T1_4 in the resource store. It has not been loaded yet.
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ShowText(IInputBytes bytes) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs:line 232
   at UglyToad.PdfPig.Graphics.Operations.TextShowing.ShowText.Run(IOperationContext operationContext) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Graphics/Operations/TextShowing/ShowText.cs:line 67
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ProcessOperations(IReadOnlyList`1 operations) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs:line 195
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.Process(Int32 pageNumberCurrent, IReadOnlyList`1 operations) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs:line 186
   at UglyToad.PdfPig.Parser.PageFactory.GetContent(Int32 pageNumber, IReadOnlyList`1 contentBytes, CropBox cropBox, UserSpaceUnit userSpaceUnit, PageRotationDegrees rotation, Boolean clipPaths, MediaBox mediaBox) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Parser/PageFactory.cs:line 174
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Parser/PageFactory.cs:line 146
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Content/Pages.cs:line 66
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/PdfDocument.cs:line 160
   at UglyToad.PdfPig.PdfDocument.GetPages()+MoveNext() in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/PdfDocument.cs:line 180
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PdfToJsonExporter.Application.GetPages(PdfDocument pdfDocument, FileInfo fileInfo) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfPig/Application.cs:line 168
```

**Comment by plaisted** [comment]
This is a valid error for the file. It will throw an error in Acrobat as well if you got to the page (8 I think?). It's missing the font in the resources dict.

**Comment by christopher5106** [comment]
Right, but viewer can still display the page. In the case of PDFPIG, it fails even for parsing single page object. So unless library modifies its behavior to not throw exception for partial failure whole page will fail. What we get at the end is a complete white page for page 8.

**Comment by EliotJones** [comment]
This is now handled by the `SkipMissingFonts` argument in parsing options in tonight's build
