### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by christopher5106** [UglyToad/PdfPig#300]
For document https://drive.google.com/file/d/1BasWgVdvnHh0mzd8JqWdcbsOpktkNF5j/view?usp=sharing
I get the following error

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at UglyToad.PdfPig.Parser.DocumentInformationFactory.GetEntryOrDefault(DictionaryToken infoDictionary, NameToken key) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Parser/DocumentInformationFactory.cs:line 41
   at UglyToad.PdfPig.Parser.DocumentInformationFactory.Create(IPdfTokenScanner pdfTokenScanner, TrailerDictionary trailer) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Parser/DocumentInformationFactory.cs:line 26
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.OpenDocument(IInputBytes inputBytes, ISeekableTokenScanner scanner, ILog log, Boolean isLenientParsing, IReadOnlyList`1 passwords, Boolean clipPaths) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Parser/PdfDocumentFactory.cs:line 140
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(IInputBytes inputBytes, ParsingOptions options) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Parser/PdfDocumentFactory.cs:line 78
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(Byte[] fileBytes, ParsingOptions options) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Parser/PdfDocumentFactory.cs:line 33
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(String filename, ParsingOptions options) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/Parser/PdfDocumentFactory.cs:line 43
   at UglyToad.PdfPig.PdfDocument.Open(String filePath, ParsingOptions options) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/PdfDocument.cs:line 130
   at PdfToJsonExporter.Application.Process(FileInfo fileInfo) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfPig/Application.cs:line 86
   at PdfToJsonExporter.Application.Process(DirectoryInfo directoryInfo) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfPig/Application.cs:line 64
   at PdfToJsonExporter.Application.Run() in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfPig/Application.cs:line 42
   at PdfToJsonExporter.Program.<>c.<Main>b__1_0(CommandLineOptions o) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfPig/Program.cs:line 18
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PdfToJsonExporter.Program.Main(String[] args) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfPig/Program.cs:line 15
```

**Comment by arty1901** [comment]
Can i work with this bug?

**Comment by EliotJones** [comment]
Closing this since I think it was fixed, let me know if you encounter any issues.
