### ISSUE TITLE
InvalidFontFormatException

### ISSUE THREAD

**Issue by christopher5106** [UglyToad/PdfPig#301]
In document https://drive.google.com/file/d/18R2jmJ4v9LcNEAV8oBTgOERXXGvC_FWO/view?usp=sharing
I get the following error:

```
UglyToad.PdfPig.Fonts.InvalidFontFormatException: The provided TrueType font dictionary did not have a /FirstChar and did not match a Standard 14 font: <BaseFont, /Arial-BoldMT,Bold>, <Encoding, /WinAnsiEncoding>, <FontDescriptor, 407 0>, <Name, /F7>, <Subtype, /TrueType>, <Type, /Font>.
   at UglyToad.PdfPig.PdfFonts.Parser.Handlers.TrueTypeFontHandler.Generate(DictionaryToken dictionary) in /mnt/c/Users/cbo/apps/document_structure_comprehension_dataset/PdfToJsonExporter/Libraries/PdfPig/src/UglyToad.PdfPig/PdfFonts/Parser/Handlers/TrueTypeFontHandler.cs:line 62
   at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary)
```

**Comment by EliotJones** [comment]
Closing this since I think it was fixed, let me know if you encounter any issues.
