### ISSUE TITLE
Fonts.Type1.Type1FontParserTests.CanReadHexEncryptedPortion Test fails

### ISSUE THREAD

**Issue by JacobMillward** [UglyToad/PdfPig#4]
**Changeset:** 7fab13e8776608545bb13e2bbe9528e17f59799f

```
Test Name:	UglyToad.PdfPig.Tests.Fonts.Type1.Type1FontParserTests.CanReadHexEncryptedPortion
Test FullName:	UglyToad.PdfPig.Tests.Fonts.Type1.Type1FontParserTests.CanReadHexEncryptedPortion
Test Source:	C:\Users\Jacob\dev\PdfPig\src\UglyToad.PdfPig.Tests\Fonts\Type1\Type1FontParserTests.cs : line 15
Test Outcome:	Failed
Test Duration:	0:00:00.005

Result StackTrace:	
at UglyToad.PdfPig.Fonts.Type1.Parser.Type1Tokenizer.ReadNextToken() in C:\Users\Jacob\dev\PdfPig\src\UglyToad.PdfPig\Fonts\Type1\Parser\Type1Tokenizer.cs:line 59
   at UglyToad.PdfPig.Fonts.Type1.Parser.Type1Tokenizer.GetNext() in C:\Users\Jacob\dev\PdfPig\src\UglyToad.PdfPig\Fonts\Type1\Parser\Type1Tokenizer.cs:line 33
   at UglyToad.PdfPig.Fonts.Type1.Parser.Type1EncryptedPortionParser.Parse(IReadOnlyList`1 bytes, Boolean isLenientParsing) in C:\Users\Jacob\dev\PdfPig\src\UglyToad.PdfPig\Fonts\Type1\Parser\Type1EncryptedPortionParser.cs:line 40
   at UglyToad.PdfPig.Fonts.Type1.Parser.Type1FontParser.Parse(IInputBytes inputBytes, Int32 length1, Int32 length2) in C:\Users\Jacob\dev\PdfPig\src\UglyToad.PdfPig\Fonts\Type1\Parser\Type1FontParser.cs:line 149
   at UglyToad.PdfPig.Tests.Fonts.Type1.Type1FontParserTests.CanReadHexEncryptedPortion() in C:\Users\Jacob\dev\PdfPig\src\UglyToad.PdfPig.Tests\Fonts\Type1\Type1FontParserTests.cs:line 19
Result Message:	System.InvalidOperationException : Encountered an end of string ')' outside of string.

```

**Comment by EliotJones** [comment]
As discussed it appears the Embedded resources feeding into the tests are being read differently on your machine vs the build server/my machine. In order to avoid this in future it's probably best to just read the files for test off-disk rather than from embedded resources.

I'll hopefully get around to changing this soon.

**Comment by EliotJones** [comment]
I've changed the type 1 font files to be content rather than embedded resources, please see if this helps at all. This commit currently has 4 failing tests but the tests you mentioned should all pass.

**Comment by EliotJones** [comment]
This should now use the files on disk rather than embedded resources which hopefully avoids the encoding issue.
