### ISSUE TITLE
Type2CharStrings parsing/intepretation error

### ISSUE THREAD

**Issue by Hert79** [UglyToad/PdfPig#451]
Document can be found here:
https://www.raco.cat/index.php/Onomastica/article/download/377544/470822/

```
pdfDocument.GetPages() throws this exception:
System.InvalidOperationException
  HResult=0x80131509
  Message=Failed to interpret charstring for symbol with name: uni011E. Commands: 295.00
-17.00
35.00
224.00
29.00
327.00
35.00
43.00
48.00
hstemhm
72.00
94.00
325.00
64.00
25.00
32.00
vstemhm
573.00
44.00
rmoveto
-13.00
6.00
-7.00
5.00
2.00
14.00
2.00
26.00
10.00
61.00
6.00
29.00
8.00
32.00
8.00
13.00
20.00
5.00
10.00
2.00
8.00
2.00
15.00
2.00
5.00
5.00
2.00
21.00
-3.00
4.00
rrcurveto
-19.00
-26.00
-3.00
-66.00
-64.00
-39.00
-26.00
hflex
-4.00
-2.00
-4.00
-22.00
3.00
-5.00
31.00
-4.00
21.00
-3.00
16.00
-3.00
22.00
-6.00
5.00
-14.00
-5.00
-33.00
-5.00
-33.00
-8.00
-51.00
-8.00
-31.00
-2.00
-10.00
-6.00
-14.00
-13.00
-8.00
rrcurveto
-9.00
-15.00
-28.00
-5.00
-21.00
hhcurveto
-139.00
-80.00
92.00
155.00
180.00
97.00
153.00
164.00
hvcurveto
hintmask
41.00
-8.00
-18.00
27.00
hvcurveto
25.00
-16.00
6.00
-26.00
-1.00
-70.00
4.00
-3.00
23.00
-1.00
5.00
6.00
6.00
44.00
17.00
68.00
12.00
37.00
-17.00
1.00
-26.00
5.00
-24.00
4.00
rrcurveto
5.00
-28.00
-50.00
7.00
-35.00
hhcurveto
-69.00
-53.00
-8.00
-26.00
-58.00
hvcurveto
-135.00
-57.00
-80.00
-136.00
-151.00
vvcurveto
-169.00
90.00
-103.00
197.00
vhcurveto
hintmask
94.00
29.00
10.00
31.00
hvcurveto
3.00
2.00
5.00
17.00
-2.00
3.00
rrcurveto
hintmask
680.00
rmoveto
-41.00
-28.00
17.00
44.00
-6.00
hvcurveto
-1.00
1.00
-9.00
0.00
-2.00
-1.00
-8.00
-2.00
-26.00
-18.00
-5.00
-9.00
rrcurveto
-50.00
-4.00
44.00
-30.00
60.00
hhcurveto
66.00
59.00
37.00
65.00
30.00
hvcurveto
1.00
-3.00
5.00
-2.00
-8.00
-16.00
-7.00
-1.00
-1.00
vhcurveto
-40.00
-35.00
-26.00
-12.00
-38.00
hhcurveto
endchar
.
  Source=UglyToad.PdfPig.Fonts
  StackTrace:
   at UglyToad.PdfPig.Fonts.CompactFontFormat.CharStrings.Type2CharStrings.Generate(String name, Double defaultWidthX, Double nominalWidthX)
   at UglyToad.PdfPig.Fonts.CompactFontFormat.CompactFontFormatFont.GetCharacterBoundingBox(String characterName)
   at UglyToad.PdfPig.PdfFonts.Simple.Type1FontSimple.GetBoundingBoxInGlyphSpace(Int32 characterCode)
   at UglyToad.PdfPig.PdfFonts.Simple.Type1FontSimple.GetBoundingBox(Int32 characterCode)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ShowText(IInputBytes bytes)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ShowPositionedText(IReadOnlyList`1 tokens)
   at UglyToad.PdfPig.Graphics.Operations.TextShowing.ShowTextsWithPositioning.Run(IOperationContext operationContext)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ProcessOperations(IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.Process(Int32 pageNumberCurrent, IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Parser.PageFactory.GetContent(Int32 pageNumber, IReadOnlyList`1 contentBytes, CropBox cropBox, UserSpaceUnit userSpaceUnit, PageRotationDegrees rotation, Boolean clipPaths, MediaBox mediaBox)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.<GetPages>d__32.MoveNext()
   at PdfToXml.PdfToXmlConverter.ConvertPdfToXml(PdfDocument pdfDocument, ProcessingOptions processingOptions) in C:\Visual Studio Projects\Visual Studio Online\CitaDel\PdfToXml\PdfToXml\PdfToXmlConverter.cs:line 122

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Cannot pop from the bottom of an empty stack, invalid charstring parsed.
```

**Comment by EliotJones** [comment]
Done in #528
