### ISSUE TITLE
Exception in method `GrahamScan` when manipulating a pdf

### ISSUE THREAD

**Issue by paillave** [UglyToad/PdfPig#458]
Sometimes, I get an exception when I try to manipulate some pdf documents with the parser.
I occurs when I "play" with words. Under the hood, the exception is raised in the method `UglyToad.PdfPig.Geometry.GeometryExtensions.GrahamScan`.

Here is a link to a sample project in dotnet fiddle: https://dotnetfiddle.net/J4MXxb

and here is the code it self
```csharp
using System;
using System.Linq;
using System.Collections.Generic;
using UglyToad.PdfPig.Core;
using UglyToad.PdfPig.Geometry;

public class Program
{
	class MyPoint
	{
		public double X { get; set; }
		public double Y { get; set; }
	}

	public static void Main()
	{
		var dataSample = "[{\"X\":134.74199999999985,\"Y\":1611.657},{\"X\":277.58043749999985,\"Y\":1611.657},{\"X\":314.74199999999985,\"Y\":1611.657},{\"X\":507.0248828124999,\"Y\":1611.657},{\"X\":545.1419999999998,\"Y\":1611.657},{\"X\":632.9658281249997,\"Y\":1611.657},{\"X\":668.5709999999998,\"Y\":1611.657},{\"X\":831.3395078125002,\"Y\":1611.657},{\"X\":868.1139999999998,\"Y\":1611.657},{\"X\":892.8907187499999,\"Y\":1611.657},{\"X\":1010.0569999999999,\"Y\":1611.6569999999997},{\"X\":1046.2174003906248,\"Y\":1611.7654812011715},{\"X\":1010.0569999999999,\"Y\":1611.657},{\"X\":1046.2174003906248,\"Y\":1611.7654812011717},{\"X\":1085.145,\"Y\":1611.8822639999996},{\"X\":1255.484941406251,\"Y\":1612.3932838242179},{\"X\":1301.144,\"Y\":1612.5302609999994},{\"X\":1359.0006406250002,\"Y\":1612.7038309218747},{\"X\":1301.144,\"Y\":1612.5302609999997},{\"X\":1359.0006406250002,\"Y\":1612.703830921875},{\"X\":1400.915,\"Y\":1612.8295739999996},{\"X\":1505.379062499999,\"Y\":1613.1429661874993},{\"X\":1400.915,\"Y\":1612.8295739999999},{\"X\":1505.379062499999,\"Y\":1613.1429661874995},{\"X\":1543.886,\"Y\":1613.2584869999996},{\"X\":1600.9401015625003,\"Y\":1613.4296493046872},{\"X\":1641.597,\"Y\":1613.5516199999997},{\"X\":1764.5577421874998,\"Y\":1613.9205022265612},{\"X\":1641.597,\"Y\":1613.55162},{\"X\":1764.5577421874998,\"Y\":1613.9205022265614}]";
		var points = System.Text.Json.JsonSerializer.Deserialize<List<MyPoint>>(dataSample).Select(p=>new PdfPoint(p.X, p.Y)).ToList();
		var result = GeometryExtensions.GrahamScan(points);
	}
}
```
The exception is this one:
```
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in System.Linq.dll: 'Specified argument was out of the range of valid values.'
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   [...]
```

The exception occurs at this very line: https://github.com/UglyToad/PdfPig/blob/ddab53e45636019b751e6b3baef079c6e48dd371/src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs#L312

**Comment by BobLd** [comment]
Hi @paillave, thanks a lot for reporting this issue and giving a sample. I'll have a look at it shortly

**Comment by BobLd** [comment]
I've created a PR to for the issue. The points you're using also showed another issue in the function that should now be fixed too

**Comment by paillave** [comment]
> I've created a PR to for the issue. The points you're using also showed another issue in the function that should now be fixed too

Great! I'll make a test tonight (GMT Paris) on your latest sources. Do you have an idea of when you will publish the change on nuget?

**Comment by paillave** [comment]
> > I've created a PR to for the issue. The points you're using also showed another issue in the function that should now be fixed too
> 
> Great! I'll make a test tonight (GMT Paris) on your latest sources. Do you have an idea of when you will publish the change on nuget (even in alpha)?

(FYI, we process ***a lot*** of PDFs with your tool on daily basis. If everything goes fine with an alpha version you would publish, I'll tell you; you will have an idea of the reliability of this version.)

**Comment by BobLd** [comment]
@paillave let me know if you face other issues on that. Leaving it close but happy to reopen if need be

**Comment by paillave** [comment]
Hi, everything seems to work using your sources.
When do you plan to have it avaible on nuget?

**Comment by paillave** [comment]
> Hi, everything seems to work using your sources. When do you plan to have it avaible on nuget?

ah ok, just saw the alpha version on nuget :)
