### ISSUE TITLE
0.1.8 crashes when reading a file

### ISSUE THREAD

**Issue by marcRobertHabib** [UglyToad/PdfPig#724]
Hi, Thanks for your work

File https://www.medikamente-per-klick.de/images/ecommerce/11/19/11194059_2017-11_de_s.pdf crashes with version 0.1.8 only on GetPages with error:

System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'index')
   at System.Collections.Generic.List`1.GetRange(Int32 index, Int32 count)
   at UglyToad.PdfPig.Functions.Type4.StackOperators.Copy.Execute(ExecutionContext context)
   at UglyToad.PdfPig.Functions.Type4.InstructionSequence.Execute(ExecutionContext context)
   at UglyToad.PdfPig.Functions.Type4.InstructionSequence.Execute(ExecutionContext context)
   at UglyToad.PdfPig.Functions.PdfFunctionType4.Eval(Double[] input)
   at UglyToad.PdfPig.Graphics.Colors.DeviceNColorSpaceDetails.GetColor(Double[] values)
   at UglyToad.PdfPig.Graphics.Colors.DeviceNColorSpaceDetails.GetInitializeColor()
   at UglyToad.PdfPig.Graphics.ColorSpaceContext.SetNonStrokingColorspace(NameToken colorspace, DictionaryToken dictionary)
   at UglyToad.PdfPig.Graphics.Operations.SetNonStrokeColorSpace.Run(IOperationContext operationContext)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ProcessOperations(IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.Process(Int32 pageNumberCurrent, IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Parser.PageFactory.GetContent(Int32 pageNumber, IReadOnlyList`1 contentBytes, CropBox cropBox, UserSpaceUnit userSpaceUnit, PageRotationDegrees rotation, MediaBox mediaBox, InternalParsingOptions parsingOptions)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, NamedDestinations namedDestinations, InternalParsingOptions parsingOptions)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, NamedDestinations namedDestinations, InternalParsingOptions parsingOptions)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.GetPages()+MoveNext()

**Comment by BobLd** [comment]
@marcRobertHabib thanks for raising the issue and providing a sample document. I've raised a PR to fix the bug

**Comment by marcRobertHabib** [comment]
Thanks

How can I get a fixed version?

**Comment by BobLd** [comment]
@marcRobertHabib you can use the latest nightly release of the NuGet package
