### ISSUE TITLE
The exception "Value cannot be null" is thrown by TokenWriter.WriteToken

### ISSUE THREAD

**Issue by ismyofficework** [UglyToad/PdfPig#743]
Hello, and **Congratulations** on the excellent work with the library!

As a user of the **PdfPig** library, I encountered an exception during the implementation of a specific PDF file. I would greatly appreciate your assistance in resolving this issue. Thank you in advance for your help.

**Exception Details:-**
`System.ArgumentNullException: Value cannot be null.
Parameter name: token
   at UglyToad.PdfPig.Writer.TokenWriter.WriteToken(IToken token, Stream outputStream) in C:\PdfPig\src\UglyToad.PdfPig\Writer\TokenWriter.cs:line 86
   at UglyToad.PdfPig.Writer.TokenWriter.WriteArray(ArrayToken array, Stream outputStream) in C:\PdfPig\src\UglyToad.PdfPig\Writer\TokenWriter.cs:line 312
   at UglyToad.PdfPig.Writer.TokenWriter.WriteToken(IToken token, Stream outputStream) in C:\PdfPig\src\UglyToad.PdfPig\Writer\TokenWriter.cs:line 91
   at UglyToad.PdfPig.Writer.TokenWriter.WriteDictionary(DictionaryToken dictionary, Stream outputStream) in C:\PdfPig\src\UglyToad.PdfPig\Writer\TokenWriter.cs:line 341
   at UglyToad.PdfPig.Writer.TokenWriter.WriteToken(IToken token, Stream outputStream) in C:\PdfPig\src\UglyToad.PdfPig\Writer\TokenWriter.cs:line 100
   at UglyToad.PdfPig.Writer.TokenWriter.WriteObject(ObjectToken objectToken, Stream outputStream) in C:\PdfPig\src\UglyToad.PdfPig\Writer\TokenWriter.cs:line 431
   at UglyToad.PdfPig.Writer.TokenWriter.WriteToken(IToken token, Stream outputStream) in C:\PdfPig\src\UglyToad.PdfPig\Writer\TokenWriter.cs:line 119
   at UglyToad.PdfPig.Writer.PdfStreamWriter.WriteToken(IToken token) in C:\PdfPig\src\UglyToad.PdfPig\Writer\PdfStreamWriter.cs:line 44
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 143
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 88
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 136
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 102
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 88
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 136
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 88
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 136
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 102
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 88
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 145
   at UglyToad.PdfPig.Writer.WriterUtil.CopyToken(IPdfStreamWriter writer, IToken tokenToCopy, IPdfTokenScanner tokenScanner, IDictionary`2 referencesFromDocument, Dictionary`2 callstack) in C:\PdfPig\src\UglyToad.PdfPig\Writer\WriterUtil.cs:line 136
   at UglyToad.PdfPig.Writer.PdfDocumentBuilder.AddPage(PdfDocument document, Int32 pageNumber) in C:\PdfPig\src\UglyToad.PdfPig\Writer\PdfDocumentBuilder.cs:line 342`

**Comment by EliotJones** [comment]
Going to close this now since we hope the linked commits resolved this.
