### ISSUE TITLE
Not all Streams support Position property

### ISSUE THREAD

**Issue by phaetto** [UglyToad/PdfPig#744]
Hey there,

The document is irrelevant, the problem comes when I want to load a pdf directly from an http Stream to parse the pdf.
Stacktrace is looking like the following:
``` 
at System.Net.Http.HttpBaseStream.get_Position()
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(Stream stream, ParsingOptions options)
   at (Custom Code)
```

and the exception is a `NotSupportedException`.

I am using version 0.1.8.

The line responsible for this is the following:
https://github.com/UglyToad/PdfPig/blob/4537ec3f02c9f1f12e17e3a2e03f411c41d027de/src/UglyToad.PdfPig/Parser/PdfDocumentFactory.cs#L48

Question: Do the Streams have to have to support Position property for this package to work?

**Comment by BobLd** [comment]
@phaetto can you have a look at the discussion in this issue https://github.com/UglyToad/PdfPig/issues/564

This looks similar, let me know if that helps

**Comment by phaetto** [comment]
@BobLd Thank you for your reply. This is similar but not exactly the same. Also I know I can use that with `MemoryStream`. I am actually using that as a workaround for now.

But I am trying to pass a Stream from http using `HttpCompletionOption.ResponseHeadersRead` and I don't want the response of a file to be in memory twice. I think this scenario is very important and should be supported.

**Comment by EliotJones** [comment]
Unfortunately because PDF parsing requires reading the file from the end (once the file header has been located at the start) and then random access throughout the file to jump to objects referred throughout the file I don't think there's any way to do this without reading the whole file into memory first, or parsing from the file system.

**Comment by phaetto** [comment]
That is a bit sad if that is the case. But thank you anyway for taking a look at it.

Feel free to close this issue if it is a no-fix.
