### ISSUE TITLE
NullReferenceException in GetPages() ... ResourceStore.GetFont()

### ISSUE THREAD

**Issue by kirk-marple** [UglyToad/PdfPig#765]
Using this file: https://arxiv.org/pdf/2108.11480.pdf

Nuget package: [0.1.9-alpha-20240128-f886e](https://www.nuget.org/packages/PdfPig/0.1.9-alpha-20240128-f886e)

Simply opening this PDF, and asking for the pages is throwing an exception getting a font, it appears.

```
using var pdoc = PdfDocument.Open(content.Stream, new ParsingOptions { SkipMissingFonts = true, UseLenientParsing = true });
var docpages = pdoc.GetPages().ToList();
```

Getting this exception thrown:
```
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at UglyToad.PdfPig.Util.StackDictionary`2.TryGetValue(K key, V& result)
   at UglyToad.PdfPig.Content.ResourceStore.GetFont(NameToken name)
   at UglyToad.PdfPig.Graphics.BaseStreamProcessor`1.ShowText(IInputBytes bytes)
   at UglyToad.PdfPig.Graphics.Operations.TextShowing.ShowText.Run(IOperationContext operationContext)
   at UglyToad.PdfPig.Graphics.BaseStreamProcessor`1.ProcessOperations(IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Graphics.BaseStreamProcessor`1.ProcessFormXObject(StreamToken formStream, NameToken xObjectName)
   at UglyToad.PdfPig.Graphics.BaseStreamProcessor`1.ApplyXObject(NameToken xObjectName)
   at UglyToad.PdfPig.Graphics.Operations.InvokeNamedXObject.Run(IOperationContext operationContext)
   at UglyToad.PdfPig.Graphics.BaseStreamProcessor`1.ProcessOperations(IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.Process(Int32 pageNumberCurrent, IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Parser.PageFactory.ProcessPage(Int32 pageNumber, DictionaryToken dictionary, NamedDestinations namedDestinations, MediaBox mediaBox, CropBox cropBox, UserSpaceUnit userSpaceUnit, PageRotationDegrees rotation, TransformationMatrix initialMatrix, IReadOnlyList`1 operations)
   at UglyToad.PdfPig.Content.BasePageFactory`1.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, NamedDestinations namedDestinations)
   at UglyToad.PdfPig.Content.Pages.GetPage[TPage](IPageFactory`1 pageFactory, Int32 pageNumber, NamedDestinations namedDestinations, ParsingOptions parsingOptions)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, NamedDestinations namedDestinations, ParsingOptions parsingOptions)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.<GetPages>d__34.MoveNext()
```

**Comment by BobLd** [comment]
@kirk-marple Thanks for creating the issue and for sharing the document, that's very helpful.

I've narrowed down the issue, it's related to failing to cast the number "1797693134862315631259457270791380001216713246039491126358296914738626428928" to a `decimal` (as it's too large) in the `NumericTokenizer` on line 156, it works well with a `double` from what I see (@EliotJones 😉)

I'm going to create a PR to try to fix that
