### ISSUE TITLE
Could not find the startxref within the last 2048 characters.

### ISSUE THREAD

**Issue by last-Programmer** [UglyToad/PdfPig#816]
I am trying to open a pdf generated by crystal reports and it is giving the error

Could not find the startxref within the last 2048 characters.

We open number of pdfs generated by Crystal Reports and it all works fine. But with one specific report we are getting this error. 

Unfortunately we are not able to get the pdf since it is a a step in a long process in production app.

The call stack shows this

 at UglyToad.PdfPig.Parser.FileStructure.FileTrailerParser.GetStartXrefPosition(IInputBytes bytes, Int32 offsetFromEnd)
   at UglyToad.PdfPig.Parser.FileStructure.FileTrailerParser.GetFirstCrossReferenceOffset(IInputBytes bytes, ISeekableTokenScanner scanner, Boolean isLenientParsing)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.OpenDocument(IInputBytes inputBytes, ISeekableTokenScanner scanner, InternalParsingOptions parsingOptions)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(IInputBytes inputBytes, ParsingOptions options)

Is there a way to fix this issue.

Thank You very much in advance.

**Comment by BobLd** [comment]
@last-Programmer can you confirm you used the latest nightly build [0.1.9-alpha-20240402-f6292](https://www.nuget.org/packages/PdfPig/0.1.9-alpha-20240402-f6292)

**Comment by last-Programmer** [comment]
@BobLd i will try the alpha version and update you. thanks.

**Comment by hoverwars** [comment]
Hello, I'm experiencing the same issue with a pdf that seems to be auto-generated. I'm using the latest alpha build: 0.1.9-alpha-20240702-65c64.

`UglyToad.PdfPig.Core.PdfDocumentFormatException: 'Could not find the startxref within the last 2048 characters.'`

Is there a way to bypass this error ?

**Comment by last-Programmer** [comment]
we have also tried with the alpha buils and the issue remains still.

**Comment by POFerro** [comment]
Hi @BobLd ,

I also have this issue, tested with 0.1.9 and tested with 0.1.10-alpha-20241008-a2580 all return this exception.
I attached a pdf that has this behavior, it's very basic but it can be read by other readers ( the pdf has a simple script on it, it shows an alert box, it's OK I was testing against a XSS attack but it's not malicious :D )
[xssPDF-1.pdf](https://github.com/user-attachments/files/17341299/xssPDF-1.pdf)

Thanks and best regards
POFerro

**Comment by BobLd** [comment]
@POFerro my antivirus is blocking the download... do you have a way to either remove the xss from the pdf, or have another pdf document example?

**Comment by POFerro** [comment]
Hi @BobLd ,
Try opening this file: 
[sample.txt](https://github.com/user-attachments/files/17392793/sample.txt)
I renamed it to txt, should be safe to download now.
Just rename it to .pdf and you should be able to reproduce

Thanks and best regards
POFerro

**Comment by shashank0x00** [comment]
@POFerro Were u able to solve this?
