### ISSUE TITLE
InvalidOperationException: 'No charstring sequence with the name /one in this font.'

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#82]
Opening the page 192 of [this](https://www.toshiba-storage.com/wp-content/uploads/2018/01/UM_Canvio_Basics.pdf) document throws `System.InvalidOperationException: 'No charstring sequence with the name /one in this font.'` in `Type2CharStrings.Generate(string name)`.

__Full details:__
System.InvalidOperationException
  HResult=0x80131509
  Message=No charstring sequence with the name /one in this font.
  Source=UglyToad.PdfPig
  StackTrace:
   at UglyToad.PdfPig.Fonts.CompactFontFormat.CharStrings.Type2CharStrings.Generate(String name) in \PdfPig\src\UglyToad.PdfPig\Fonts\CompactFontFormat\CharStrings\Type2CharStrings.cs:line 63
   at UglyToad.PdfPig.Fonts.CompactFontFormat.CompactFontFormatFont.<>c__DisplayClass16_0.<GetCharacterBoundingBox>b__1(Type2CharStrings x) in \PdfPig\src\UglyToad.PdfPig\Fonts\CompactFontFormat\CompactFontFormatFont.cs:line 41
   at UglyToad.PdfPig.Util.Union'2.Case2.Match(Action'1 first, Action'1 second) in \PdfPig\src\UglyToad.PdfPig\Util\Union.cs:line 56
   at UglyToad.PdfPig.Fonts.CompactFontFormat.CompactFontFormatFont.GetCharacterBoundingBox(String characterName) in \PdfPig\src\UglyToad.PdfPig\Fonts\CompactFontFormat\CompactFontFormatFont.cs:line 40
   at UglyToad.PdfPig.Fonts.CompactFontFormat.CompactFontFormatFontProgram.GetCharacterBoundingBox(String characterName) in \PdfPig\src\UglyToad.PdfPig\Fonts\CompactFontFormat\CompactFontFormatFontProgram.cs:line 48
   at UglyToad.PdfPig.Fonts.Simple.Type1FontSimple.<>c__DisplayClass20_0.<GetBoundingBoxInGlyphSpace>b__1(CompactFontFormatFontProgram x) in \PdfPig\src\UglyToad.PdfPig\Fonts\Simple\Type1FontSimple.cs:line 185
   at UglyToad.PdfPig.Util.Union'2.Case2.Match(Action'1 first, Action'1 second) in \PdfPig\src\UglyToad.PdfPig\Util\Union.cs:line 56
   at UglyToad.PdfPig.Fonts.Simple.Type1FontSimple.GetBoundingBoxInGlyphSpace(Int32 characterCode) in \PdfPig\src\UglyToad.PdfPig\Fonts\Simple\Type1FontSimple.cs:line 169
   at UglyToad.PdfPig.Fonts.Simple.Type1FontSimple.GetBoundingBox(Int32 characterCode) in \PdfPig\src\UglyToad.PdfPig\Fonts\Simple\Type1FontSimple.cs:line 124
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ShowText(IInputBytes bytes) in \PdfPig\src\UglyToad.PdfPig\Graphics\ContentStreamProcessor.cs:line 198
   at UglyToad.PdfPig.Graphics.Operations.TextShowing.ShowText.Run(IOperationContext operationContext) in \PdfPig\src\UglyToad.PdfPig\Graphics\Operations\TextShowing\ShowText.cs:line 68
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.ProcessOperations(IReadOnlyList'1 operations) in \PdfPig\src\UglyToad.PdfPig\Graphics\ContentStreamProcessor.cs:line 111
   at UglyToad.PdfPig.Graphics.ContentStreamProcessor.Process(IReadOnlyList'1 operations) in \PdfPig\src\UglyToad.PdfPig\Graphics\ContentStreamProcessor.cs:line 102
   at UglyToad.PdfPig.Parser.PageFactory.GetContent(IReadOnlyList'1 contentBytes, CropBox cropBox, UserSpaceUnit userSpaceUnit, PageRotationDegrees rotation, Boolean isLenientParsing) in \PdfPig\src\UglyToad.PdfPig\Parser\PageFactory.cs:line 129
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean isLenientParsing) in \PdfPig\src\UglyToad.PdfPig\Parser\PageFactory.cs:line 112
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber) in \PdfPig\src\UglyToad.PdfPig\Content\Pages.cs:line 66
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) in \PdfPig\src\UglyToad.PdfPig\PdfDocument.cs:line 150

**Comment by EliotJones** [comment]
It looks like the fonts are getting the wrong labels assigned in the resource state due to multiple resource dictionaries causing reassignment of the `T1_0` label from `31 0 R` to `48 0 R`.

I will need to improve the handling of resource dictionary loading in order to fix this, I'm just noting the cause of the problem here so I don't forget.

**Comment by EliotJones** [comment]
Hi, this should be fixed now, please give the latest version a try.

**Comment by BobLd** [comment]
Hi Eliot, I confirm it now works!
