### ISSUE TITLE
Exception when trying to recognize a non cross reference stream as a cross reference stream

### ISSUE THREAD

**Issue by Greybird** [UglyToad/PdfPig#902]
When the parser is trying to recognize a stream as a cross reference stream, without guarantee of success, it can happen that the code throws an exception, when encounteing a filter where the Decode method throws for example.
```
System.NotSupportedException
The DST (Discrete Cosine Transform) Filter indicates data is encoded in JPEG format. This filter is not currently supported but the raw data can be supplied to JPEG supporting libraries.
   at UglyToad.PdfPig.Filters.DctDecodeFilter.Decode(ReadOnlySpan`1 input, DictionaryToken streamDictionary, Int32 filterIndex) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\Filters\DctDecodeFilter.cs:line 14
   at UglyToad.PdfPig.PdfExtensions.Decode(StreamToken stream, IFilterProvider filterProvider) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\PdfExtensions.cs:line 66
   at UglyToad.PdfPig.Parser.Parts.CrossReference.CrossReferenceStreamParser.Parse(Int64 streamOffset, Nullable`1 fromTableAtOffset, StreamToken stream) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\Parser\Parts\CrossReference\CrossReferenceStreamParser.cs:line 23
   at UglyToad.PdfPig.Parser.FileStructure.CrossReferenceParser.TryParseCrossReferenceStream(Int64 objByteOffset, IPdfTokenScanner pdfScanner, Nullable`1 fromTableAtOffset, CrossReferenceTablePart& xrefTablePart) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\Parser\FileStructure\CrossReferenceParser.cs:line 273
   at UglyToad.PdfPig.Parser.FileStructure.CrossReferenceParser.Parse(IInputBytes bytes, Boolean isLenientParsing, Int64 crossReferenceLocation, Int64 offsetCorrection, IPdfTokenScanner pdfScanner, ISeekableTokenScanner tokenScanner) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\Parser\FileStructure\CrossReferenceParser.cs:line 160
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.OpenDocument(IInputBytes inputBytes, ISeekableTokenScanner scanner, ParsingOptions parsingOptions) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\Parser\PdfDocumentFactory.cs:line 135
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(IInputBytes inputBytes, ParsingOptions options) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\Parser\PdfDocumentFactory.cs:line 99
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(Byte[] fileBytes, ParsingOptions options) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\Parser\PdfDocumentFactory.cs:line 33
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(String filename, ParsingOptions options) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\Parser\PdfDocumentFactory.cs:line 43
   at UglyToad.PdfPig.PdfDocument.Open(String filePath, ParsingOptions options) in C:\Code\External\PdfPig\src\UglyToad.PdfPig\PdfDocument.cs:line 113
```
As failure to find a cross reference stream is acceptable, it should not throw.

**Comment by Greybird** [comment]
Sorry, this is due to another change I made beforehand, that made the issue appear. Time to have some sleep.
