### ISSUE TITLE
System.ArgumentOutOfRangeException - Format4CMapTable constructor

### ISSUE THREAD

**Issue by davidpene** [UglyToad/PdfPig#91]
Error occurs when parsing a pdf exported from google docs.

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at UglyToad.PdfPig.Fonts.TrueType.Tables.CMapSubTables.Format4CMapTable..ctor(TrueTypeCMapPlatform platformId, Int32 encodingId, Int32 language, IReadOnlyList`1 segments, IReadOnlyList`1 glyphIds)
   at UglyToad.PdfPig.Fonts.TrueType.Tables.CMapSubTables.Format4CMapTable.Load(TrueTypeDataBytes data, TrueTypeCMapPlatform platformId, Int32 encodingId)
   at UglyToad.PdfPig.Fonts.TrueType.Parser.CMapTableParser.Parse(TrueTypeHeaderTable header, TrueTypeDataBytes data, Builder register)
   at UglyToad.PdfPig.Fonts.TrueType.Parser.TableParser.Parse[T](TrueTypeHeaderTable table, TrueTypeDataBytes data, Builder register)
   at UglyToad.PdfPig.Fonts.TrueType.Parser.TrueTypeFontParser.OptionallyParseTables(IReadOnlyDictionary`2 tables, TrueTypeDataBytes data, Builder tableRegister)
   at UglyToad.PdfPig.Fonts.TrueType.Parser.TrueTypeFontParser.ParseTables(Decimal version, IReadOnlyDictionary`2 tables, TrueTypeDataBytes data)
   at UglyToad.PdfPig.Fonts.TrueType.Parser.TrueTypeFontParser.Parse(TrueTypeDataBytes data)
   at UglyToad.PdfPig.Fonts.Parser.Parts.CidFontFactory.ReadDescriptorFile(FontDescriptor descriptor)
   at UglyToad.PdfPig.Fonts.Parser.Parts.CidFontFactory.Generate(DictionaryToken dictionary, Boolean isLenientParsing)
   at UglyToad.PdfPig.Fonts.Parser.Handlers.Type0FontHandler.Generate(DictionaryToken dictionary, Boolean isLenientParsing)
   at UglyToad.PdfPig.Fonts.FontFactory.Get(DictionaryToken dictionary, Boolean isLenientParsing)
   at UglyToad.PdfPig.Content.ResourceContainer.LoadFontDictionary(DictionaryToken fontDictionary, Boolean isLenientParsing)
   at UglyToad.PdfPig.Content.ResourceContainer.LoadResourceDictionary(DictionaryToken resourceDictionary, Boolean isLenientParsing)
   at UglyToad.PdfPig.Parser.PageFactory.LoadResources(DictionaryToken dictionary, Boolean isLenientParsing)
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean isLenientParsing)
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber)
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
```

[Fail PDF 02.pdf](https://github.com/UglyToad/PdfPig/files/3924500/Fail.PDF.02.pdf)

**Comment by davidpene** [comment]
@EliotJones

**Comment by davidpene** [comment]
This is how it's used, and the error occurs when doing `document.GetPage`
```
        public DocumentSigningPosition[] GetDocumentSigningPositions(string file)
        {
            var docText = "";
            using (PdfDocument document = PdfDocument.Open(new MemoryStream(Convert.FromBase64String(file))))
            {
                for (var i = 0; i < document.NumberOfPages; i++)
                {
                    var page = document.GetPage(i + 1);
                    docText += page.Text;
                }
            }
            return FindSigners(docText).Select(x => new DocumentSigningPosition(Guid.NewGuid(), Guid.Empty, x)).ToArray();
        }

        public List<string> FindSigners(string text)
        {
            var regex = new Regex(@"{{(?:[\w\s]*_es_:(\w+):signature\s*|\s*#\w+=es:(\w+):signature\s*)}}");
            var signatureKeys = new List<string>();
            foreach (Match match in regex.Matches(text))
            {
                for (var i = 1; i < match.Groups.Count; i++)
                {
                    if (match.Groups[i].Success) signatureKeys.Add(match.Groups[i].Value);
                }
            }
            return signatureKeys;
        }
```

**Comment by EliotJones** [comment]
Thanks for the issue report, this should be fixed in the version attached to this comment, please try it out and let me know if it works ok.

[PdfPig.0.0.9.91.zip](https://github.com/UglyToad/PdfPig/files/3927483/PdfPig.0.0.9.91.zip)

**Comment by davidpene** [comment]
Awesome! It works. Thanks @EliotJones 

Are you going to publish a new version?

**Comment by EliotJones** [comment]
Glad to hear it worked.

The next release, 0.0.10, will be soon, ideally before Christmas. I just want to squish some more of the open bugs before releasing to hopefully have a quite stable release.

I'll leave this open until the official release to make sure it actually happens.

**Comment by davidpene** [comment]
Thanks @EliotJones we are hoping to have a release before Xmas, and this would be a golden nugget for us.

**Comment by EliotJones** [comment]
Hi, the latest version 0.0.10 has been released today: https://www.nuget.org/packages/PdfPig/

Release notes for this version are here: https://github.com/UglyToad/PdfPig/releases/tag/v0.0.10

Please give it a go when you have time and let me know if it works :)

**Comment by davidpene** [comment]
Everything works as expected thanks @EliotJones for the quick turn around. Appreciate it.

**Comment by EliotJones** [comment]
Thanks, I'll close this one now.
