### ISSUE TITLE
PdfDocumentFormatException: Could not find the object number 750 0 with type DictionaryToken instead, it was found with type ObjectToken.

### ISSUE THREAD

**Issue by Sayayaya** [UglyToad/PdfPig#926]
PDFPig can't read the attached PDF Document.

I have tried in 0.1.8 and 0.1.9

```
UglyToad.PdfPig.Core.PdfDocumentFormatException: Could not find the object number 750 0 with type DictionaryToken instead, it was found with type ObjectToken.
   at UglyToad.PdfPig.Parser.Parts.DirectObjectFinder.Get[T](IndirectReference reference, IPdfTokenScanner scanner)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.ParseTrailer(CrossReferenceTable crossReferenceTable, Boolean isLenientParsing, IPdfTokenScanner pdfTokenScanner, EncryptionDictionary& encryptionDictionary)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.OpenDocument(IInputBytes inputBytes, ISeekableTokenScanner scanner, InternalParsingOptions parsingOptions)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(IInputBytes inputBytes, ParsingOptions options)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(Byte[] fileBytes, ParsingOptions options)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(String filename, ParsingOptions options)
   at UglyToad.PdfPig.PdfDocument.Open(String filePath, ParsingOptions options)
```

```
using (PdfDocument document = PdfDocument.Open(filePath))
```

Where filePath is the path to the attached PDF document

[2408.16296v1.pdf](https://github.com/user-attachments/files/17437730/2408.16296v1.pdf)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by BobLd** [comment]
Fixed in #1072
