### ISSUE TITLE
Could not find the startxref within the last 2048 characters reading pdf

### ISSUE THREAD

**Issue by kobruleht** [UglyToad/PdfPig#958]
Trying to extract text from attached PDF using

```
UglyToad.PdfPig.PdfDocument.Open(pdfStream, new UglyToad.PdfPig.ParsingOptions() { SkipMissingFonts = true });
```

throws exception

 Meetod GetStartXrefPosition
UglyToad.PdfPig.Core.PdfDocumentFormatException: Could not find the startxref within the last 2048 characters.
   at UglyToad.PdfPig.Parser.FileStructure.FileTrailerParser.GetStartXrefPosition(IInputBytes bytes, Int32 offsetFromEnd)
   at UglyToad.PdfPig.Parser.FileStructure.FileTrailerParser.GetFirstCrossReferenceOffset(IInputBytes bytes, ISeekableTokenScanner scanner, Boolean isLenientParsing)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.OpenDocument(IInputBytes inputBytes, ISeekableTokenScanner scanner, ParsingOptions parsingOptions)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(IInputBytes inputBytes, ParsingOptions options)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(Stream stream, ParsingOptions options)
   at UglyToad.PdfPig.PdfDocument.Open(Stream stream, ParsingOptions options)
[Could not find the startxref within the last 2048 characters.pdf](https://github.com/user-attachments/files/18203954/Could.not.find.the.startxref.within.the.last.2048.characters.pdf)

**Comment by BobLd** [comment]
@kobruleht I am not able to reproduce the issue with the latest pre-release version of PdfPig. Can you give it a go? I'll close the issue but feel free to re-open if need be
