### ISSUE TITLE
OperatorToken static dictionary is not thread safe

### ISSUE THREAD

**Issue by davidpene** [UglyToad/PdfPig#97]
Receiving an error when API is serving multiple requests at once.
Error occurs when calling `PdfDocument.GetPage` which initialises a new OperatorToken which access the static dictionary inside the private constructor.

```
System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at UglyToad.PdfPig.Tokens.OperatorToken..ctor(String data) in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\Tokens\OperatorToken.cs:line 27
   at UglyToad.PdfPig.Tokens.OperatorToken.Create(String data) in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\Tokens\OperatorToken.cs:line 67
   at UglyToad.PdfPig.Tokenization.PlainTokenizer.TryTokenize(Byte currentByte, IInputBytes inputBytes, IToken& token) in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\Tokenization\PlainTokenizer.cs:line 55
   at UglyToad.PdfPig.Tokenization.Scanner.CoreTokenScanner.MoveNext() in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\Tokenization\Scanner\CoreTokenScanner.cs:line 157
   at UglyToad.PdfPig.Parser.PageContentParser.Parse(IInputBytes inputBytes) in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\Parser\PageContentParser.cs:line 26
   at UglyToad.PdfPig.Parser.PageFactory.GetContent(IReadOnlyList`1 contentBytes, CropBox cropBox, UserSpaceUnit userSpaceUnit, Boolean isLenientParsing) in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\Parser\PageFactory.cs:line 109
   at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean isLenientParsing) in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\Parser\PageFactory.cs:line 86
   at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber) in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\Content\Pages.cs:line 63
   at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) in C:\git\UglyToad.PdfPig\src\UglyToad.PdfPig\PdfDocument.cs:line 123
```

**Comment by EliotJones** [comment]
Hi there, sorry about this.

I'll try and have fixed version out including the commit for this issue by either Friday 13th or Saturday 14th December.

**Comment by EliotJones** [comment]
As ever in software there's been a delay with this. I'll try to get it done by tomorrow.

**Comment by davidpene** [comment]
No worries @EliotJones appreciate the effort 🥇

**Comment by EliotJones** [comment]
The version containing this fix is now available: https://www.nuget.org/packages/PdfPig/

Please give it a go and close this issue if it works for you, thanks.

**Comment by EliotJones** [comment]
Closing this now since I assume it's working ok?
